name: music-composition-api

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - numpy==1.19
  - jupyter
  #- fluidsynth
  - pip

  - pip:
    - git+https://github.com/0xf0f/pyfluidsynth
    - git+https://github.com/tensorflow/magenta.git
    - -e ./
    - -r requirements.txt
