name: music-composition-api

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - numpy==1.19
  - jupyter
  #- fluidsynth
  - pip

  - pip:
    - git+https://github.com/0xf0f/pyfluidsynth
    - git+https://github.com/tensorflow/magenta.git
    - coolname==1.1.0
    - Flask==1.1.2
    - Flask-Cors==3.0.8
    - Flask-Session==0.3.1
    - glob2==0.7
    - ipdb
    - lazyme==0.0.23
    - matplotlib
    - midi2audio==0.1.1
    - music21==6.7.1
    - pandas==1.0.3
    - pretty-midi==0.2.9
    - pytest
    - note-seq==0.0.2
    - tqdm==4.54.0
    - visual-midi==1.1.0
    - xlrd==1.2.0
